title: Cristalino Caatinga Dry Forest beta diversity
logo: /raw/master/docs/Figs./Map_Caatinga_2.png
description: Cristalino Caatinga Forest beta diversity.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
