title: Cristalino Caatinga Dry Forest beta diversity
Studie area: "https://github.com/Tai-Rocha/Caatinga_Dry_Forest.github.io/raw/gh-pages/fig/Map_Caatinga_Cristalino.png"
description: Cristalino Caatinga Forest beta diversity.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
