title: Cristalino Caatinga Dry Forest beta diversity
Studie area:/fig/Map_Caatinga_Cristalino.png
description: Cristalino Caatinga Forest beta diversity.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
